/** รูปจาก https://tripoomsinghaart.framer.website/ (framerusercontent.com) */
const img = (id: string, ext: "jpg" | "png" | "webp" = "jpg") =>
  `https://framerusercontent.com/images/${id}.${ext}`;

export const FRAMER_IMAGES = {
  heroBackground: img("QOyIKsQm5mJHf49jrHwTdYvaZw"),
  heroOverlay: img("yZ8PusDUeagQQOcag4bjalNa3s"),
  portrait: "/portfolio/portrait.jpg",
  mark: img("7YeaErjr2kmowmTSNVyINY9EPY", "png"),
  experience: {
    goTheExtraMile: img("SD9KRLzYOj0WRG6WA8VsY8j47M"),
    clickMotion: img("vS1HMSzk40UennRxB2pPWLPjLk"),
    shortgun: img("oWfmUWK2P5y51g0duvph7cjhOgs"),
  },
  reelThumbs: {
    y2024: img("VtuWjJBpGDvfpOmZzT0JtRlM2c"),
    y2023: img("TZIwdPVWSJLeqQsHwaKT2BRqLGY"),
    y2022: img("ljtZea2GNHNBVhlno3Zxf4xhHaU"),
    y2021: img("AFJ53rZdTILMbuyNZQ8YIPoXQME"),
    y2020: img("bA4paoOmqJYH5ajhrTZy0UXMNE"),
    y2019: img("J8cKuNA5fY2S8QHd3UVGHyas"),
    adsMotion: img("7YeaErjr2kmowmTSNVyINY9EPY", "png"),
  },
} as const;

/** โลโก้แบรนด์จากสไลด์ Experience working with brands */
export const FRAMER_BRAND_LOGOS: { src: string; alt: string }[] = [
  { src: img("0zwEmB0g4931WOAHARvBgVeBmYY"), alt: "Brand" },
  { src: img("1u3onfEzfr55Hodk6WG1dtLZZTw"), alt: "Brand" },
  { src: img("2wxGDsItfHOWbjPGo8X0qtCQ6qU"), alt: "Brand" },
  { src: img("3czAN5jbQdzd8cSbrNX8q1dypE"), alt: "Brand" },
  { src: img("4ay2suMcaGlpEEGD9Kaq85JX1A"), alt: "Brand" },
  { src: img("4HvSYEhYhl4wMLH91ExEz7dIN0"), alt: "Brand" },
  { src: img("5b9yNk75xrltSFXSQNcJ20jCsO8"), alt: "Brand" },
  { src: img("5ysDJjzoShjejEtv1EAYUheVEU"), alt: "Brand" },
  { src: img("8uPvx3AEVW9tcYGXxyPscfi6pM"), alt: "Brand" },
  { src: img("bF4IlB2s39g1y2KrDe31g3TBk"), alt: "Brand" },
  { src: img("bmYnGmBlfkcZkrVYi0JCyRa28lE", "png"), alt: "Brand" },
  { src: img("bqleenXluXhQVS0rHUgPt0GsU"), alt: "Brand" },
  { src: img("CYSyuG2ldcuoQkLf19J7iQziHo"), alt: "Brand" },
  { src: img("evdQNNghXroaOmrTC3ZaErzUvLc"), alt: "Brand" },
  { src: img("FdcbPTAZQI3SPJYypDoNOUCS16s"), alt: "Brand" },
  { src: img("fN1Po34s6nWFDCNjCD6BMCoDYys"), alt: "Brand" },
  { src: img("FQ3evzT9eDqKYga9kq3wncQY6Y", "png"), alt: "Brand" },
  { src: img("FRN6VJ9zh5KpKaIefpTWqaPc6A"), alt: "Brand" },
  { src: img("hxQCtddK55qj29B19WTXPqegs"), alt: "Brand" },
  { src: img("hZTqyHfbnA1NLLgeGhVQvGcT30"), alt: "Brand" },
  { src: img("I7OH6aiABk8DiMxG3HA8sjFFlX0"), alt: "Brand" },
  { src: img("itGSgELIaOKPPhR9kZDS9RL1XMM"), alt: "Brand" },
  { src: img("Kaqmsfw2NrhKNMpE4uMUic4xYDE"), alt: "Brand" },
  { src: img("kePCxxgBGpJukRN7Fj1fK0GoM"), alt: "Brand" },
  { src: img("LD7VJM52LIshUbOuVPiww4TpPQ"), alt: "Brand" },
  { src: img("OcHddLnOw2XDsAPxEWwblcOHw"), alt: "Brand" },
  { src: img("osiahv4ZxbvJyr6pt99W2ZCZm8"), alt: "Brand" },
  { src: img("OVG1Zl5lsw231JOR3aEJYX2Y"), alt: "Brand" },
  { src: img("p6naiHFhY7yzxEIsIe49or6ShfI"), alt: "Brand" },
  { src: img("pDPm3gqOGaRhjRDQ4cLjpExHw"), alt: "Brand" },
  { src: img("QgHWi0YBChueY39dxpVDZf82bIg"), alt: "Brand" },
  { src: img("RN9EGOvlspWeIQkwUIVeXF3H7gs"), alt: "Brand" },
  { src: img("rWCxeAnHj5HD3WAJAOdi6yjxJG0"), alt: "Brand" },
  { src: img("S0t12be5hOl77Zzx9eHu2eE0Bk"), alt: "Brand" },
  { src: img("SjkVw8Zv5GKPKvskDsgM5KXyd48"), alt: "Brand" },
  { src: img("SPqSyVlafV8Q1HRvWxNyWMNDDf4"), alt: "Brand" },
  { src: img("SyPtTe09l5LyoMX7YVvf8rTQsI"), alt: "Brand" },
  { src: img("T5kL3mTqnz6jX04Yug8pktOUMuw"), alt: "Brand" },
  { src: img("UAt4E9ul0nQjmh67vcev4d5Hs"), alt: "Brand" },
  { src: img("uEglmclmdEioVMBFwFSfL7fBdRY"), alt: "Brand" },
  { src: img("V0uSdLEg4TrkqapcwJf6ia669ZU"), alt: "Brand" },
  { src: img("V5zCB44xT88k70reDtFfMtYXxgA"), alt: "Brand" },
  { src: img("WDT8iGtodu4p1VAutbumEfBUFw"), alt: "Brand" },
  { src: img("YKrxx6ka6s25o35n0l39CCKgLI"), alt: "Brand" },
  { src: img("YMFoNLyfyZmpu0gUdzAcqmEzbJE"), alt: "Brand" },
  { src: img("z8KRrpqdS6wCcvQq8q7P8nbT4TQ"), alt: "Brand" },
];
